title: Mayur Khadde
url: https://bashlogs.github.io

# Owner/author information
owner:
  name: Mayur Khadde
  avatar: IMG202401141416201.jpg
  # bio: Two roads diverged in woods, I took the one less traveled by.
  email: mayurkhadde49@gmail.com
  cv: https://bashlogs.github.io/file/Resume.pdf
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter: mayurkhadde
  github: bashlogs
  linkedin: mayur-khadde
  # scholar: 
  # bilibili: 
  # researchgate: 
  # facebook: 
  # instagram: 
  # lastfm:
  # tumblr:
  # For Google Authorship https://plus.google.com/authorship
  # google_plus:

# Analytics and webmaster tools stuff goes here
# https://search.google.com/search-console/ownership
google_verify: "SkiyuGpJOKT74vv5GmXLvYXXDkXy4v8VWPtbelYz3Hs"

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# bing_verify: ""

# Links to include in top navigation
# For external links add external: true
links:
  - title: About Me
    url: /
  - title: Projects
    url: /projects/
  - title: Publications
    url: /publications/
  - title: Blogs
    url: /blogs/
  - title: Awards
    url: /awards/
  # - title: Hobbies
  #   url: /hobbies/

  # - title: Teams
  #   url: /teams/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Kolkata
future: true
highlighter: rouge
# markdown: kramdown
# markdown: redcarpet
# pygments: true


# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  # coderay:
  #   coderay_line_numbers:
  #   coderay_line_numbers_start: 1
  #   coderay_tab_width: 4
  #   coderay_bold_every: 10
  #   coderay_css: class


# disqus settings:
disqus:
  shortname: lancecai

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "minimal-mistakes.sublime-project", "minimal-mistakes.sublime-workspace"]
